
["car:bio_diesel"]
	efficiency = 100
["immersiveengineering:biodiesel"]
	efficiency = 100
["immersivepetroleum:diesel"]
	efficiency = 100
["immersivepetroleum:diesel_sulfur"]
	efficiency = 70
["immersivepetroleum:gasoline"]
	efficiency = 90
["immersivepetroleum:oil"]
	efficiency = 50
["minecraft:lava"]
	efficiency = 10
["immersiveengineering:creosote"]
	efficiency = 60